apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1h0s
  chart:
    spec:
      chart: grafana
      version: "8.x.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h0s
  values:
    adminUser: admin
    adminPassword: admin123
    plugins:
      - victoriametrics-logs-datasource
    service:
      type: NodePort
      nodePort: 30300
    persistence:
      enabled: true
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaMetrics
            type: prometheus
            url: http://victoria-metrics-victoria-metrics-single-server.victoria-metrics.svc.cluster.local:8428
            access: proxy
            isDefault: true
          - name: VictoriaLogs
            type: victoriametrics-logs-datasource
            url: http://victoria-logs-victoria-logs-single-server.victoria-logs.svc.cluster.local:9428
            access: proxy
    grafana.ini:
      server:
        root_url: http://localhost:30300
      security:
        allow_embedding: true
