apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - harbor/namespace.yaml
  - harbor/helmrepo.yaml
  - harbor/helmrelease.yaml
  - victoria-metrics/namespace.yaml
  - victoria-metrics/helmrepo.yaml
  - victoria-metrics/scrape-config.yaml
  - victoria-metrics/helmrelease.yaml
  - victoria-logs/namespace.yaml
  - victoria-logs/helmrelease.yaml
  - otel/namespace.yaml
  - otel/helmrepo.yaml
  - otel/helmrelease.yaml
  - grafana/namespace.yaml
  - grafana/helmrepo.yaml
  - grafana/helmrelease.yaml
  - kube-state-metrics/namespace.yaml
  - kube-state-metrics/helmrepo.yaml
  - kube-state-metrics/helmrelease.yaml
  - node-exporter/helmrelease.yaml
