apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-scrape-config
  namespace: victoria-metrics
data:
  scrape.yaml: |
    global:
      scrape_interval: 30s

    scrape_configs:
      - job_name: ubuntu-host
        static_configs:
          - targets:
              - 192.168.0.105:9100
            labels:
              instance: yohannes-ubuntu
